# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'daisydate.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QFrame,
    QHBoxLayout, QLabel, QLineEdit, QMainWindow,
    QPushButton, QScrollArea, QSizePolicy, QSpinBox,
    QStackedWidget, QTextEdit, QVBoxLayout, QWidget)
from assets import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(400, 700)
        MainWindow.setMinimumSize(QSize(400, 700))
        MainWindow.setMaximumSize(QSize(400, 700))
        MainWindow.setStyleSheet(u"#centralwidget {\n"
"	background-color: #ffffff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"	background-color: #d9d9d9;\n"
"    border-radius: 8px;\n"
"	padding-left: 10px;\n"
"}\n"
"\n"
"QTextEdit {\n"
"	background-color: #d9d9d9;\n"
"    border-radius: 8px;\n"
"	padding-left: 10px;\n"
"}\n"
"\n"
"QComboBox {\n"
"	background-color: #d9d9d9;\n"
"    border-radius: 8px;\n"
"	padding-left: 10px;\n"
"}\n"
"\n"
"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 400, 700))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.page.setStyleSheet(u"")
        self.btnSignin = QPushButton(self.page)
        self.btnSignin.setObjectName(u"btnSignin")
        self.btnSignin.setGeometry(QRect(20, 610, 360, 45))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.btnSignin.setFont(font)
        self.btnSignin.setStyleSheet(u"background-color: #EBCE38;\n"
"color: #2c2c2c")
        self.icon_daisy = QLabel(self.page)
        self.icon_daisy.setObjectName(u"icon_daisy")
        self.icon_daisy.setGeometry(QRect(120, 60, 151, 161))
        self.icon_daisy.setPixmap(QPixmap(u":/images/images/yellow-daisy.png"))
        self.icon_daisy.setScaledContents(True)
        self.text_description = QLabel(self.page)
        self.text_description.setObjectName(u"text_description")
        self.text_description.setGeometry(QRect(120, 300, 152, 22))
        font1 = QFont()
        font1.setPointSize(12)
        self.text_description.setFont(font1)
        self.text_description.setStyleSheet(u"color: #2c2c2c")
        self.btnSignup = QPushButton(self.page)
        self.btnSignup.setObjectName(u"btnSignup")
        self.btnSignup.setGeometry(QRect(20, 550, 360, 45))
        self.btnSignup.setFont(font)
        self.btnSignup.setStyleSheet(u"background-color: #2c2c2c;\n"
"color: #EBCE38\n"
"\n"
"")
        self.text_daisydate = QLabel(self.page)
        self.text_daisydate.setObjectName(u"text_daisydate")
        self.text_daisydate.setEnabled(True)
        self.text_daisydate.setGeometry(QRect(90, 230, 213, 64))
        font2 = QFont()
        font2.setPointSize(36)
        self.text_daisydate.setFont(font2)
        self.text_daisydate.setStyleSheet(u"color: #2c2c2c")
        self.stackedWidget.addWidget(self.page)
        self.signin = QWidget()
        self.signin.setObjectName(u"signin")
        self.signin.setStyleSheet(u"")
        self.text_welcome = QLabel(self.signin)
        self.text_welcome.setObjectName(u"text_welcome")
        self.text_welcome.setGeometry(QRect(120, 60, 166, 32))
        font3 = QFont()
        font3.setFamilies([u"Segoe UI Semibold"])
        font3.setPointSize(18)
        font3.setBold(True)
        self.text_welcome.setFont(font3)
        self.lineEdit_email = QLineEdit(self.signin)
        self.lineEdit_email.setObjectName(u"lineEdit_email")
        self.lineEdit_email.setGeometry(QRect(30, 130, 340, 30))
        self.lineEdit_password = QLineEdit(self.signin)
        self.lineEdit_password.setObjectName(u"lineEdit_password")
        self.lineEdit_password.setGeometry(QRect(30, 180, 340, 30))
        self.lineEdit_password.setFrame(True)
        self.lineEdit_password.setEchoMode(QLineEdit.Password)
        self.lineEdit_password.setCursorPosition(0)
        self.lineEdit_password.setClearButtonEnabled(False)
        self.btnBackSignin = QPushButton(self.signin)
        self.btnBackSignin.setObjectName(u"btnBackSignin")
        self.btnBackSignin.setGeometry(QRect(20, 20, 20, 20))
        icon = QIcon()
        icon.addFile(u":/icons/icons/back.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnBackSignin.setIcon(icon)
        self.btnBackSignin.setAutoDefault(False)
        self.btnBackSignin.setFlat(True)
        self.btnSign_in = QPushButton(self.signin)
        self.btnSign_in.setObjectName(u"btnSign_in")
        self.btnSign_in.setGeometry(QRect(20, 610, 360, 45))
        self.btnSign_in.setFont(font)
        self.btnSign_in.setStyleSheet(u"background-color: #EBCE38;\n"
"color: #2c2c2c")
        self.label_signin_error = QLabel(self.signin)
        self.label_signin_error.setObjectName(u"label_signin_error")
        self.label_signin_error.setEnabled(True)
        self.label_signin_error.setGeometry(QRect(90, 230, 226, 16))
        self.label_signin_error.setStyleSheet(u"color: red")
        self.label_signin_error.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.signin)
        self.signup_phone = QWidget()
        self.signup_phone.setObjectName(u"signup_phone")
        self.btnBackSignup = QPushButton(self.signup_phone)
        self.btnBackSignup.setObjectName(u"btnBackSignup")
        self.btnBackSignup.setGeometry(QRect(20, 20, 20, 20))
        self.btnBackSignup.setIcon(icon)
        self.btnBackSignup.setAutoDefault(False)
        self.btnBackSignup.setFlat(True)
        self.text_welcome2 = QLabel(self.signup_phone)
        self.text_welcome2.setObjectName(u"text_welcome2")
        self.text_welcome2.setGeometry(QRect(75, 60, 249, 32))
        self.text_welcome2.setFont(font3)
        self.btnGetStarted = QPushButton(self.signup_phone)
        self.btnGetStarted.setObjectName(u"btnGetStarted")
        self.btnGetStarted.setGeometry(QRect(20, 610, 360, 45))
        self.btnGetStarted.setFont(font)
        self.btnGetStarted.setStyleSheet(u"background-color: #EBCE38;\n"
"color: #2c2c2c")
        self.label_signup_error = QLabel(self.signup_phone)
        self.label_signup_error.setObjectName(u"label_signup_error")
        self.label_signup_error.setEnabled(True)
        self.label_signup_error.setGeometry(QRect(90, 230, 226, 16))
        self.label_signup_error.setStyleSheet(u"color: red")
        self.label_signup_error.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineEditPassword = QLineEdit(self.signup_phone)
        self.lineEditPassword.setObjectName(u"lineEditPassword")
        self.lineEditPassword.setGeometry(QRect(30, 180, 340, 30))
        self.lineEditPassword.setFrame(True)
        self.lineEditPassword.setEchoMode(QLineEdit.Password)
        self.lineEditPassword.setCursorPosition(0)
        self.lineEditPassword.setClearButtonEnabled(False)
        self.lineEditEmail = QLineEdit(self.signup_phone)
        self.lineEditEmail.setObjectName(u"lineEditEmail")
        self.lineEditEmail.setGeometry(QRect(30, 130, 340, 30))
        self.stackedWidget.addWidget(self.signup_phone)
        self.signup_birthday = QWidget()
        self.signup_birthday.setObjectName(u"signup_birthday")
        self.btnNext = QPushButton(self.signup_birthday)
        self.btnNext.setObjectName(u"btnNext")
        self.btnNext.setGeometry(QRect(20, 610, 360, 45))
        self.btnNext.setFont(font)
        self.btnNext.setStyleSheet(u"background-color: #EBCE38;\n"
"color: #2c2c2c")
        self.label_bd = QLabel(self.signup_birthday)
        self.label_bd.setObjectName(u"label_bd")
        self.label_bd.setGeometry(QRect(80, 60, 239, 32))
        self.label_bd.setFont(font3)
        self.btnBackBD = QPushButton(self.signup_birthday)
        self.btnBackBD.setObjectName(u"btnBackBD")
        self.btnBackBD.setGeometry(QRect(20, 20, 20, 20))
        self.btnBackBD.setIcon(icon)
        self.btnBackBD.setAutoDefault(False)
        self.btnBackBD.setFlat(True)
        self.dateEdit = QDateEdit(self.signup_birthday)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(70, 130, 261, 31))
        self.dateEdit.setStyleSheet(u"background-color: #d9d9d9;\n"
"padding-left: 10px;\n"
"border-radius: 8px")
        self.dateEdit.setDateTime(QDateTime(QDate(2006, 1, 1), QTime(16, 0, 0)))
        self.label_age_error = QLabel(self.signup_birthday)
        self.label_age_error.setObjectName(u"label_age_error")
        self.label_age_error.setEnabled(True)
        self.label_age_error.setGeometry(QRect(50, 180, 300, 16))
        self.label_age_error.setStyleSheet(u"color: red")
        self.stackedWidget.addWidget(self.signup_birthday)
        self.signup_info = QWidget()
        self.signup_info.setObjectName(u"signup_info")
        self.btnAlmostDone = QPushButton(self.signup_info)
        self.btnAlmostDone.setObjectName(u"btnAlmostDone")
        self.btnAlmostDone.setGeometry(QRect(20, 610, 360, 45))
        self.btnAlmostDone.setFont(font)
        self.btnAlmostDone.setStyleSheet(u"background-color: #EBCE38;\n"
"color: #2c2c2c")
        self.text_info = QLabel(self.signup_info)
        self.text_info.setObjectName(u"text_info")
        self.text_info.setGeometry(QRect(100, 60, 192, 32))
        self.text_info.setFont(font3)
        self.btnBackInfo = QPushButton(self.signup_info)
        self.btnBackInfo.setObjectName(u"btnBackInfo")
        self.btnBackInfo.setGeometry(QRect(20, 20, 20, 20))
        self.btnBackInfo.setIcon(icon)
        self.btnBackInfo.setAutoDefault(False)
        self.btnBackInfo.setFlat(True)
        self.lineEdit_name = QLineEdit(self.signup_info)
        self.lineEdit_name.setObjectName(u"lineEdit_name")
        self.lineEdit_name.setGeometry(QRect(60, 130, 280, 30))
        self.lineEdit_name.setStyleSheet(u"color: #666666")
        self.lineEdit_name.setCursorPosition(0)
        self.comboBox_gender = QComboBox(self.signup_info)
        self.comboBox_gender.addItem("")
        self.comboBox_gender.addItem("")
        self.comboBox_gender.addItem("")
        self.comboBox_gender.addItem("")
        self.comboBox_gender.setObjectName(u"comboBox_gender")
        self.comboBox_gender.setGeometry(QRect(60, 180, 280, 30))
        self.comboBox_gender.setToolTipDuration(0)
        self.comboBox_gender.setStyleSheet(u"color: #666666")
        self.comboBox_showGender = QComboBox(self.signup_info)
        self.comboBox_showGender.addItem("")
        self.comboBox_showGender.addItem("")
        self.comboBox_showGender.addItem("")
        self.comboBox_showGender.addItem("")
        self.comboBox_showGender.setObjectName(u"comboBox_showGender")
        self.comboBox_showGender.setGeometry(QRect(60, 230, 280, 30))
        self.comboBox_showGender.setStyleSheet(u"color: #666666")
        self.stackedWidget.addWidget(self.signup_info)
        self.signup_photo = QWidget()
        self.signup_photo.setObjectName(u"signup_photo")
        self.btnWelcome = QPushButton(self.signup_photo)
        self.btnWelcome.setObjectName(u"btnWelcome")
        self.btnWelcome.setGeometry(QRect(20, 610, 360, 45))
        self.btnWelcome.setFont(font)
        self.btnWelcome.setStyleSheet(u"background-color: #EBCE38;\n"
"color: #2c2c2c")
        self.text_add_photo = QLabel(self.signup_photo)
        self.text_add_photo.setObjectName(u"text_add_photo")
        self.text_add_photo.setGeometry(QRect(110, 60, 181, 32))
        self.text_add_photo.setFont(font3)
        self.btnBackPhoto = QPushButton(self.signup_photo)
        self.btnBackPhoto.setObjectName(u"btnBackPhoto")
        self.btnBackPhoto.setGeometry(QRect(20, 20, 20, 20))
        self.btnBackPhoto.setIcon(icon)
        self.btnBackPhoto.setAutoDefault(False)
        self.btnBackPhoto.setFlat(True)
        self.photo1 = QLabel(self.signup_photo)
        self.photo1.setObjectName(u"photo1")
        self.photo1.setGeometry(QRect(30, 130, 220, 220))
        self.photo1.setFont(font1)
        self.photo1.setCursor(QCursor(Qt.PointingHandCursor))
        self.photo1.setStyleSheet(u"background-color: #d9d9d9")
        self.photo1.setAlignment(Qt.AlignCenter)
        self.photo2 = QLabel(self.signup_photo)
        self.photo2.setObjectName(u"photo2")
        self.photo2.setGeometry(QRect(270, 130, 100, 100))
        font4 = QFont()
        font4.setPointSize(9)
        self.photo2.setFont(font4)
        self.photo2.setCursor(QCursor(Qt.PointingHandCursor))
        self.photo2.setStyleSheet(u"background-color: #d9d9d9")
        self.photo2.setAlignment(Qt.AlignCenter)
        self.photo3 = QLabel(self.signup_photo)
        self.photo3.setObjectName(u"photo3")
        self.photo3.setGeometry(QRect(270, 250, 100, 100))
        self.photo3.setCursor(QCursor(Qt.PointingHandCursor))
        self.photo3.setStyleSheet(u"background-color: #d9d9d9")
        self.photo3.setAlignment(Qt.AlignCenter)
        self.photo4 = QLabel(self.signup_photo)
        self.photo4.setObjectName(u"photo4")
        self.photo4.setGeometry(QRect(30, 370, 100, 100))
        self.photo4.setCursor(QCursor(Qt.PointingHandCursor))
        self.photo4.setStyleSheet(u"background-color: #d9d9d9")
        self.photo4.setAlignment(Qt.AlignCenter)
        self.photo5 = QLabel(self.signup_photo)
        self.photo5.setObjectName(u"photo5")
        self.photo5.setGeometry(QRect(150, 370, 100, 100))
        self.photo5.setCursor(QCursor(Qt.PointingHandCursor))
        self.photo5.setStyleSheet(u"background-color: #d9d9d9")
        self.photo5.setAlignment(Qt.AlignCenter)
        self.photo6 = QLabel(self.signup_photo)
        self.photo6.setObjectName(u"photo6")
        self.photo6.setGeometry(QRect(270, 370, 100, 100))
        self.photo6.setCursor(QCursor(Qt.PointingHandCursor))
        self.photo6.setStyleSheet(u"background-color: #d9d9d9")
        self.photo6.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.signup_photo)
        self.suggested = QWidget()
        self.suggested.setObjectName(u"suggested")
        self.horizontalLayoutWidget = QWidget(self.suggested)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(0, 650, 401, 51))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.btnSuggested = QPushButton(self.horizontalLayoutWidget)
        self.btnSuggested.setObjectName(u"btnSuggested")
        icon1 = QIcon()
        icon1.addFile(u":/icons/icons/suggested-select.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnSuggested.setIcon(icon1)
        self.btnSuggested.setIconSize(QSize(24, 24))

        self.horizontalLayout.addWidget(self.btnSuggested)

        self.btnDiscover = QPushButton(self.horizontalLayoutWidget)
        self.btnDiscover.setObjectName(u"btnDiscover")
        self.btnDiscover.setEnabled(True)
        icon2 = QIcon()
        icon2.addFile(u":/icons/icons/discover.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnDiscover.setIcon(icon2)
        self.btnDiscover.setIconSize(QSize(24, 24))

        self.horizontalLayout.addWidget(self.btnDiscover)

        self.btnChat = QPushButton(self.horizontalLayoutWidget)
        self.btnChat.setObjectName(u"btnChat")
        self.btnChat.setEnabled(True)
        icon3 = QIcon()
        icon3.addFile(u":/icons/icons/chat.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnChat.setIcon(icon3)
        self.btnChat.setIconSize(QSize(24, 24))

        self.horizontalLayout.addWidget(self.btnChat)

        self.btnAccount = QPushButton(self.horizontalLayoutWidget)
        self.btnAccount.setObjectName(u"btnAccount")
        self.btnAccount.setEnabled(True)
        icon4 = QIcon()
        icon4.addFile(u":/icons/icons/account.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnAccount.setIcon(icon4)
        self.btnAccount.setIconSize(QSize(24, 24))
        self.btnAccount.setFlat(False)

        self.horizontalLayout.addWidget(self.btnAccount)

        self.topbar_suggested = QWidget(self.suggested)
        self.topbar_suggested.setObjectName(u"topbar_suggested")
        self.topbar_suggested.setGeometry(QRect(0, 0, 400, 70))
        self.topbar_suggested.setStyleSheet(u"#topbar_suggested {\n"
"	border-bottom: 1px solid #d9d9d9;\n"
"}")
        self.text_suggested = QLabel(self.topbar_suggested)
        self.text_suggested.setObjectName(u"text_suggested")
        self.text_suggested.setGeometry(QRect(160, 30, 77, 22))
        font5 = QFont()
        font5.setFamilies([u"Segoe UI Semibold"])
        font5.setPointSize(12)
        font5.setBold(True)
        self.text_suggested.setFont(font5)
        self.text_suggested.setStyleSheet(u"color: #2c2c2c")
        self.btnPreferences = QPushButton(self.topbar_suggested)
        self.btnPreferences.setObjectName(u"btnPreferences")
        self.btnPreferences.setEnabled(True)
        self.btnPreferences.setGeometry(QRect(354, 30, 24, 24))
        self.btnPreferences.setStyleSheet(u"")
        icon5 = QIcon()
        icon5.addFile(u":/icons/icons/setting-config.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnPreferences.setIcon(icon5)
        self.btnPreferences.setFlat(True)
        self.scrollArea = QScrollArea(self.suggested)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(0, 70, 400, 581))
        self.scrollArea.setStyleSheet(u"background-color: #ffffff")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 398, 579))
        self.user_image = QLabel(self.scrollAreaWidgetContents)
        self.user_image.setObjectName(u"user_image")
        self.user_image.setGeometry(QRect(0, 0, 400, 400))
        self.user_image.setStyleSheet(u"background-color: #EBCE38")
        self.label_age = QLabel(self.scrollAreaWidgetContents)
        self.label_age.setObjectName(u"label_age")
        self.label_age.setGeometry(QRect(42, 443, 13, 16))
        self.label_age.setStyleSheet(u"color: #707070")
        self.label_school = QLabel(self.scrollAreaWidgetContents)
        self.label_school.setObjectName(u"label_school")
        self.label_school.setGeometry(QRect(20, 415, 41, 18))
        self.label_school.setFont(font)
        self.label_school.setStyleSheet(u"color: #454545")
        self.icon_cake = QLabel(self.scrollAreaWidgetContents)
        self.icon_cake.setObjectName(u"icon_cake")
        self.icon_cake.setGeometry(QRect(20, 440, 14, 17))
        self.icon_cake.setPixmap(QPixmap(u":/icons/icons/cake.png"))
        self.hr1_2 = QFrame(self.scrollAreaWidgetContents)
        self.hr1_2.setObjectName(u"hr1_2")
        self.hr1_2.setGeometry(QRect(20, 460, 361, 20))
        self.hr1_2.setStyleSheet(u"color: #d9d9d9")
        self.hr1_2.setFrameShape(QFrame.HLine)
        self.hr1_2.setFrameShadow(QFrame.Raised)
        self.btn_fw_photo = QPushButton(self.scrollAreaWidgetContents)
        self.btn_fw_photo.setObjectName(u"btn_fw_photo")
        self.btn_fw_photo.setGeometry(QRect(205, 370, 50, 20))
        self.btn_fw_photo.setStyleSheet(u"background-color: rgba(255, 255, 255, 0.5);")
        self.btn_bk_photo = QPushButton(self.scrollAreaWidgetContents)
        self.btn_bk_photo.setObjectName(u"btn_bk_photo")
        self.btn_bk_photo.setGeometry(QRect(145, 370, 50, 20))
        self.btn_bk_photo.setStyleSheet(u"background-color: rgba(255, 255, 255, 0.5);")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_2 = QWidget(self.suggested)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(100, 590, 201, 51))
        self.horizontalLayout_4 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.btnDislike = QPushButton(self.horizontalLayoutWidget_2)
        self.btnDislike.setObjectName(u"btnDislike")
        icon6 = QIcon()
        icon6.addFile(u":/icons/icons/dislike.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnDislike.setIcon(icon6)
        self.btnDislike.setIconSize(QSize(40, 40))

        self.horizontalLayout_4.addWidget(self.btnDislike)

        self.btnFlower = QPushButton(self.horizontalLayoutWidget_2)
        self.btnFlower.setObjectName(u"btnFlower")
        icon7 = QIcon()
        icon7.addFile(u":/icons/icons/btn-flower.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnFlower.setIcon(icon7)
        self.btnFlower.setIconSize(QSize(40, 40))

        self.horizontalLayout_4.addWidget(self.btnFlower)

        self.btnLike = QPushButton(self.horizontalLayoutWidget_2)
        self.btnLike.setObjectName(u"btnLike")
        icon8 = QIcon()
        icon8.addFile(u":/icons/icons/like.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnLike.setIcon(icon8)
        self.btnLike.setIconSize(QSize(40, 40))

        self.horizontalLayout_4.addWidget(self.btnLike)

        self.stackedWidget.addWidget(self.suggested)
        self.preferences = QWidget()
        self.preferences.setObjectName(u"preferences")
        self.topbar_preferences = QWidget(self.preferences)
        self.topbar_preferences.setObjectName(u"topbar_preferences")
        self.topbar_preferences.setGeometry(QRect(0, 0, 400, 70))
        self.topbar_preferences.setStyleSheet(u"#topbar_preferences {\n"
"	border-bottom: 1px solid #d9d9d9;\n"
"}")
        self.btnBackPref = QPushButton(self.topbar_preferences)
        self.btnBackPref.setObjectName(u"btnBackPref")
        self.btnBackPref.setGeometry(QRect(20, 20, 20, 20))
        self.btnBackPref.setIcon(icon)
        self.btnBackPref.setAutoDefault(False)
        self.btnBackPref.setFlat(True)
        self.text_type = QLabel(self.preferences)
        self.text_type.setObjectName(u"text_type")
        self.text_type.setGeometry(QRect(20, 90, 155, 26))
        font6 = QFont()
        font6.setFamilies([u"Segoe UI Semibold"])
        font6.setPointSize(14)
        font6.setBold(True)
        self.text_type.setFont(font6)
        self.text_type.setStyleSheet(u"color: #454545")
        self.text_preferences = QLabel(self.preferences)
        self.text_preferences.setObjectName(u"text_preferences")
        self.text_preferences.setGeometry(QRect(20, 120, 321, 41))
        font7 = QFont()
        font7.setPointSize(10)
        self.text_preferences.setFont(font7)
        self.text_preferences.setStyleSheet(u"color: #666666")
        self.hr1 = QFrame(self.preferences)
        self.hr1.setObjectName(u"hr1")
        self.hr1.setGeometry(QRect(20, 170, 361, 20))
        self.hr1.setStyleSheet(u"color: #d9d9d9")
        self.hr1.setFrameShape(QFrame.HLine)
        self.hr1.setFrameShadow(QFrame.Raised)
        self.comboBoxGender = QComboBox(self.preferences)
        self.comboBoxGender.addItem("")
        self.comboBoxGender.addItem("")
        self.comboBoxGender.addItem("")
        self.comboBoxGender.addItem("")
        self.comboBoxGender.setObjectName(u"comboBoxGender")
        self.comboBoxGender.setGeometry(QRect(20, 200, 361, 31))
        self.comboBoxGender.setStyleSheet(u"color: #666666")
        self.text_age = QLabel(self.preferences)
        self.text_age.setObjectName(u"text_age")
        self.text_age.setGeometry(QRect(30, 275, 23, 18))
        self.text_age.setFont(font7)
        self.text_age.setStyleSheet(u"color: #666666")
        self.spinBox_min = QSpinBox(self.preferences)
        self.spinBox_min.setObjectName(u"spinBox_min")
        self.spinBox_min.setGeometry(QRect(270, 270, 42, 31))
        self.spinBox_min.setFont(font7)
        self.spinBox_min.setMinimum(18)
        self.spinBox_max = QSpinBox(self.preferences)
        self.spinBox_max.setObjectName(u"spinBox_max")
        self.spinBox_max.setGeometry(QRect(340, 270, 42, 31))
        self.spinBox_max.setFont(font7)
        self.spinBox_max.setMinimum(18)
        self.spinBox_max.setValue(99)
        self.text_to = QLabel(self.preferences)
        self.text_to.setObjectName(u"text_to")
        self.text_to.setGeometry(QRect(320, 275, 12, 18))
        self.text_to.setFont(font7)
        self.text_to.setStyleSheet(u"color: #666666")
        self.hr2 = QFrame(self.preferences)
        self.hr2.setObjectName(u"hr2")
        self.hr2.setGeometry(QRect(20, 240, 361, 20))
        self.hr2.setStyleSheet(u"color: #d9d9d9")
        self.hr2.setFrameShape(QFrame.HLine)
        self.hr2.setFrameShadow(QFrame.Raised)
        self.hr3 = QFrame(self.preferences)
        self.hr3.setObjectName(u"hr3")
        self.hr3.setGeometry(QRect(20, 310, 361, 20))
        self.hr3.setStyleSheet(u"color: #d9d9d9")
        self.hr3.setFrameShape(QFrame.HLine)
        self.hr3.setFrameShadow(QFrame.Raised)
        self.hr4 = QFrame(self.preferences)
        self.hr4.setObjectName(u"hr4")
        self.hr4.setGeometry(QRect(20, 380, 361, 20))
        self.hr4.setStyleSheet(u"color: #d9d9d9")
        self.hr4.setFrameShape(QFrame.HLine)
        self.hr4.setFrameShadow(QFrame.Raised)
        self.comboBoxRG = QComboBox(self.preferences)
        self.comboBoxRG.addItem("")
        self.comboBoxRG.addItem("")
        self.comboBoxRG.addItem("")
        self.comboBoxRG.addItem("")
        self.comboBoxRG.addItem("")
        self.comboBoxRG.setObjectName(u"comboBoxRG")
        self.comboBoxRG.setGeometry(QRect(20, 340, 361, 31))
        self.comboBoxRG.setStyleSheet(u"color: #666666")
        self.stackedWidget.addWidget(self.preferences)
        self.discover = QWidget()
        self.discover.setObjectName(u"discover")
        self.topbar_discover = QWidget(self.discover)
        self.topbar_discover.setObjectName(u"topbar_discover")
        self.topbar_discover.setGeometry(QRect(0, 0, 400, 70))
        self.topbar_discover.setStyleSheet(u"#topbar_discover {\n"
"	border-bottom: 1px solid #d9d9d9;\n"
"}")
        self.text_discover = QLabel(self.topbar_discover)
        self.text_discover.setObjectName(u"text_discover")
        self.text_discover.setGeometry(QRect(170, 30, 62, 22))
        self.text_discover.setFont(font5)
        self.text_discover.setStyleSheet(u"color: #2c2c2c")
        self.btnSearch = QPushButton(self.topbar_discover)
        self.btnSearch.setObjectName(u"btnSearch")
        self.btnSearch.setGeometry(QRect(354, 30, 24, 24))
        self.btnSearch.setStyleSheet(u"")
        icon9 = QIcon()
        icon9.addFile(u":/icons/icons/search.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnSearch.setIcon(icon9)
        self.icon_flower = QLabel(self.topbar_discover)
        self.icon_flower.setObjectName(u"icon_flower")
        self.icon_flower.setGeometry(QRect(20, 35, 16, 16))
        self.icon_flower.setPixmap(QPixmap(u":/icons/icons/flower.png"))
        self.icon_flower.setScaledContents(True)
        self.text_flower = QLabel(self.topbar_discover)
        self.text_flower.setObjectName(u"text_flower")
        self.text_flower.setGeometry(QRect(40, 35, 20, 16))
        self.text_flower.setStyleSheet(u"color: #EBCE38")
        self.horizontalLayoutWidget_3 = QWidget(self.discover)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(0, 650, 401, 51))
        self.horizontalLayout_5 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.btnSuggested_2 = QPushButton(self.horizontalLayoutWidget_3)
        self.btnSuggested_2.setObjectName(u"btnSuggested_2")
        icon10 = QIcon()
        icon10.addFile(u":/icons/icons/suggested.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnSuggested_2.setIcon(icon10)
        self.btnSuggested_2.setIconSize(QSize(24, 24))

        self.horizontalLayout_5.addWidget(self.btnSuggested_2)

        self.btnDiscover_2 = QPushButton(self.horizontalLayoutWidget_3)
        self.btnDiscover_2.setObjectName(u"btnDiscover_2")
        self.btnDiscover_2.setEnabled(True)
        icon11 = QIcon()
        icon11.addFile(u":/icons/icons/discover-select.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnDiscover_2.setIcon(icon11)
        self.btnDiscover_2.setIconSize(QSize(24, 24))

        self.horizontalLayout_5.addWidget(self.btnDiscover_2)

        self.btnChat_2 = QPushButton(self.horizontalLayoutWidget_3)
        self.btnChat_2.setObjectName(u"btnChat_2")
        self.btnChat_2.setEnabled(True)
        self.btnChat_2.setIcon(icon3)
        self.btnChat_2.setIconSize(QSize(24, 24))

        self.horizontalLayout_5.addWidget(self.btnChat_2)

        self.btnAccount_2 = QPushButton(self.horizontalLayoutWidget_3)
        self.btnAccount_2.setObjectName(u"btnAccount_2")
        self.btnAccount_2.setEnabled(True)
        self.btnAccount_2.setIcon(icon4)
        self.btnAccount_2.setIconSize(QSize(24, 24))

        self.horizontalLayout_5.addWidget(self.btnAccount_2)

        self.scrollArea_2 = QScrollArea(self.discover)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setGeometry(QRect(0, 70, 400, 581))
        self.scrollArea_2.setStyleSheet(u"background-color: #ffffff")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 398, 579))
        self.widget_people = QWidget(self.scrollAreaWidgetContents_2)
        self.widget_people.setObjectName(u"widget_people")
        self.widget_people.setGeometry(QRect(40, 20, 320, 391))
        self.widget_people.setStyleSheet(u"#widget_people {\n"
"	border: 1px solid #d9d9d9;	\n"
"	border-radius: 10px\n"
"}")
        self.btnFlowerDiscover = QPushButton(self.widget_people)
        self.btnFlowerDiscover.setObjectName(u"btnFlowerDiscover")
        self.btnFlowerDiscover.setGeometry(QRect(270, 340, 41, 41))
        self.btnFlowerDiscover.setIcon(icon7)
        self.btnFlowerDiscover.setIconSize(QSize(40, 40))
        self.label_photo = QLabel(self.widget_people)
        self.label_photo.setObjectName(u"label_photo")
        self.label_photo.setGeometry(QRect(0, 0, 320, 320))
        self.label_photo.setStyleSheet(u"border-top-left-radius: 10px;\n"
"   border-top-right-radius: 10px;\n"
"background-color: #EBCE38")
        self.text_school = QLabel(self.widget_people)
        self.text_school.setObjectName(u"text_school")
        self.text_school.setGeometry(QRect(20, 330, 41, 18))
        self.text_school.setFont(font)
        self.text_school.setStyleSheet(u"color: #454545")
        self.label_cake = QLabel(self.widget_people)
        self.label_cake.setObjectName(u"label_cake")
        self.label_cake.setGeometry(QRect(20, 355, 14, 17))
        self.label_cake.setPixmap(QPixmap(u":/icons/icons/cake.png"))
        self.label_age_discover = QLabel(self.widget_people)
        self.label_age_discover.setObjectName(u"label_age_discover")
        self.label_age_discover.setGeometry(QRect(42, 358, 13, 16))
        self.label_age_discover.setStyleSheet(u"color: #707070")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.stackedWidget.addWidget(self.discover)
        self.search = QWidget()
        self.search.setObjectName(u"search")
        self.topbar_search = QWidget(self.search)
        self.topbar_search.setObjectName(u"topbar_search")
        self.topbar_search.setGeometry(QRect(0, 0, 400, 70))
        self.topbar_search.setStyleSheet(u"#topbar_search {\n"
"	border-bottom: 1px solid #d9d9d9;\n"
"}")
        self.text_search = QLabel(self.topbar_search)
        self.text_search.setObjectName(u"text_search")
        self.text_search.setGeometry(QRect(175, 30, 49, 22))
        self.text_search.setFont(font5)
        self.text_search.setStyleSheet(u"color: #2c2c2c")
        self.btnApply = QPushButton(self.topbar_search)
        self.btnApply.setObjectName(u"btnApply")
        self.btnApply.setGeometry(QRect(345, 35, 34, 19))
        self.btnApply.setFont(font7)
        self.btnApply.setStyleSheet(u"color: #EBCE38")
        self.btnCancel = QPushButton(self.topbar_search)
        self.btnCancel.setObjectName(u"btnCancel")
        self.btnCancel.setGeometry(QRect(20, 35, 38, 19))
        self.btnCancel.setFont(font7)
        self.btnCancel.setStyleSheet(u"color: #EBCE38")
        self.spinBoxMin = QSpinBox(self.search)
        self.spinBoxMin.setObjectName(u"spinBoxMin")
        self.spinBoxMin.setGeometry(QRect(270, 110, 42, 31))
        self.spinBoxMin.setFont(font7)
        self.spinBoxMin.setMinimum(18)
        self.frame_5 = QFrame(self.search)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(20, 150, 361, 20))
        self.frame_5.setStyleSheet(u"color: #d9d9d9")
        self.frame_5.setFrameShape(QFrame.HLine)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.frame_6 = QFrame(self.search)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(20, 220, 361, 20))
        self.frame_6.setStyleSheet(u"color: #d9d9d9")
        self.frame_6.setFrameShape(QFrame.HLine)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.label_age_search = QLabel(self.search)
        self.label_age_search.setObjectName(u"label_age_search")
        self.label_age_search.setGeometry(QRect(30, 115, 23, 18))
        self.label_age_search.setFont(font7)
        self.label_age_search.setStyleSheet(u"color: #666666")
        self.label_9 = QLabel(self.search)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(320, 115, 12, 18))
        self.label_9.setFont(font7)
        self.label_9.setStyleSheet(u"color: #666666")
        self.comboBox_school = QComboBox(self.search)
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.addItem("")
        self.comboBox_school.setObjectName(u"comboBox_school")
        self.comboBox_school.setGeometry(QRect(20, 180, 361, 31))
        self.comboBox_school.setStyleSheet(u"color: #666666")
        self.spinBoxMax = QSpinBox(self.search)
        self.spinBoxMax.setObjectName(u"spinBoxMax")
        self.spinBoxMax.setGeometry(QRect(340, 110, 42, 31))
        self.spinBoxMax.setFont(font7)
        self.spinBoxMax.setMinimum(18)
        self.spinBoxMax.setValue(99)
        self.frame_7 = QFrame(self.search)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(20, 80, 361, 20))
        self.frame_7.setStyleSheet(u"color: #d9d9d9")
        self.frame_7.setFrameShape(QFrame.HLine)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.stackedWidget.addWidget(self.search)
        self.chat = QWidget()
        self.chat.setObjectName(u"chat")
        self.horizontalLayoutWidget_4 = QWidget(self.chat)
        self.horizontalLayoutWidget_4.setObjectName(u"horizontalLayoutWidget_4")
        self.horizontalLayoutWidget_4.setGeometry(QRect(0, 650, 401, 51))
        self.horizontalLayout_6 = QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.btnSuggested_3 = QPushButton(self.horizontalLayoutWidget_4)
        self.btnSuggested_3.setObjectName(u"btnSuggested_3")
        self.btnSuggested_3.setIcon(icon10)
        self.btnSuggested_3.setIconSize(QSize(24, 24))

        self.horizontalLayout_6.addWidget(self.btnSuggested_3)

        self.btnDiscover_3 = QPushButton(self.horizontalLayoutWidget_4)
        self.btnDiscover_3.setObjectName(u"btnDiscover_3")
        self.btnDiscover_3.setEnabled(True)
        self.btnDiscover_3.setIcon(icon2)
        self.btnDiscover_3.setIconSize(QSize(24, 24))

        self.horizontalLayout_6.addWidget(self.btnDiscover_3)

        self.btnChat_3 = QPushButton(self.horizontalLayoutWidget_4)
        self.btnChat_3.setObjectName(u"btnChat_3")
        self.btnChat_3.setEnabled(True)
        icon12 = QIcon()
        icon12.addFile(u":/icons/icons/chat-select.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnChat_3.setIcon(icon12)
        self.btnChat_3.setIconSize(QSize(24, 24))

        self.horizontalLayout_6.addWidget(self.btnChat_3)

        self.btnAccount_3 = QPushButton(self.horizontalLayoutWidget_4)
        self.btnAccount_3.setObjectName(u"btnAccount_3")
        self.btnAccount_3.setEnabled(True)
        self.btnAccount_3.setIcon(icon4)
        self.btnAccount_3.setIconSize(QSize(24, 24))

        self.horizontalLayout_6.addWidget(self.btnAccount_3)

        self.topbar_chat = QWidget(self.chat)
        self.topbar_chat.setObjectName(u"topbar_chat")
        self.topbar_chat.setGeometry(QRect(0, 0, 400, 70))
        self.topbar_chat.setStyleSheet(u"border-bottom: 1px solid #d9d9d9;")
        self.text_chat = QLabel(self.topbar_chat)
        self.text_chat.setObjectName(u"text_chat")
        self.text_chat.setGeometry(QRect(185, 30, 34, 22))
        self.text_chat.setFont(font5)
        self.text_chat.setStyleSheet(u"color: #2c2c2c")
        self.scrollArea_3 = QScrollArea(self.chat)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setGeometry(QRect(0, 70, 400, 581))
        self.scrollArea_3.setStyleSheet(u"background-color: #ffffff")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 398, 579))
        self.chatWidget = QWidget(self.scrollAreaWidgetContents_3)
        self.chatWidget.setObjectName(u"chatWidget")
        self.chatWidget.setGeometry(QRect(0, 0, 400, 80))
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.stackedWidget.addWidget(self.chat)
        self.chat_inside = QWidget()
        self.chat_inside.setObjectName(u"chat_inside")
        self.topbar_chat_inside = QWidget(self.chat_inside)
        self.topbar_chat_inside.setObjectName(u"topbar_chat_inside")
        self.topbar_chat_inside.setGeometry(QRect(0, 0, 400, 70))
        self.topbar_chat_inside.setStyleSheet(u"#topbar_chat_inside {\n"
"	border-bottom: 1px solid #d9d9d9;\n"
"}")
        self.text_user_name = QLabel(self.topbar_chat_inside)
        self.text_user_name.setObjectName(u"text_user_name")
        self.text_user_name.setGeometry(QRect(180, 30, 44, 22))
        self.text_user_name.setFont(font5)
        self.text_user_name.setStyleSheet(u"color: #2c2c2c")
        self.btnBackChat = QPushButton(self.topbar_chat_inside)
        self.btnBackChat.setObjectName(u"btnBackChat")
        self.btnBackChat.setGeometry(QRect(20, 20, 20, 20))
        self.btnBackChat.setIcon(icon)
        self.btnBackChat.setAutoDefault(False)
        self.btnBackChat.setFlat(True)
        self.widget_7 = QWidget(self.chat_inside)
        self.widget_7.setObjectName(u"widget_7")
        self.widget_7.setGeometry(QRect(0, 650, 401, 51))
        self.widget_7.setStyleSheet(u"background-color: #EBCE38")
        self.lineEditChat = QLineEdit(self.widget_7)
        self.lineEditChat.setObjectName(u"lineEditChat")
        self.lineEditChat.setGeometry(QRect(10, 10, 351, 31))
        self.lineEditChat.setStyleSheet(u"background-color: #ffffff")
        self.btnSend = QPushButton(self.widget_7)
        self.btnSend.setObjectName(u"btnSend")
        self.btnSend.setGeometry(QRect(365, 15, 30, 20))
        icon13 = QIcon()
        icon13.addFile(u":/icons/icons/send.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnSend.setIcon(icon13)
        self.btnSend.setIconSize(QSize(18, 18))
        self.verticalLayoutWidget = QWidget(self.chat_inside)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(0, 70, 401, 581))
        self.chatBoxLayOut = QVBoxLayout(self.verticalLayoutWidget)
        self.chatBoxLayOut.setObjectName(u"chatBoxLayOut")
        self.chatBoxLayOut.setContentsMargins(0, 0, 0, 0)
        self.stackedWidget.addWidget(self.chat_inside)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.horizontalLayoutWidget_5 = QWidget(self.page_2)
        self.horizontalLayoutWidget_5.setObjectName(u"horizontalLayoutWidget_5")
        self.horizontalLayoutWidget_5.setGeometry(QRect(0, 650, 401, 51))
        self.horizontalLayout_7 = QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.btnSuggested_4 = QPushButton(self.horizontalLayoutWidget_5)
        self.btnSuggested_4.setObjectName(u"btnSuggested_4")
        self.btnSuggested_4.setIcon(icon10)
        self.btnSuggested_4.setIconSize(QSize(24, 24))

        self.horizontalLayout_7.addWidget(self.btnSuggested_4)

        self.btnDiscover_4 = QPushButton(self.horizontalLayoutWidget_5)
        self.btnDiscover_4.setObjectName(u"btnDiscover_4")
        self.btnDiscover_4.setEnabled(True)
        self.btnDiscover_4.setIcon(icon2)
        self.btnDiscover_4.setIconSize(QSize(24, 24))

        self.horizontalLayout_7.addWidget(self.btnDiscover_4)

        self.btnChat_4 = QPushButton(self.horizontalLayoutWidget_5)
        self.btnChat_4.setObjectName(u"btnChat_4")
        self.btnChat_4.setEnabled(True)
        self.btnChat_4.setIcon(icon3)
        self.btnChat_4.setIconSize(QSize(24, 24))

        self.horizontalLayout_7.addWidget(self.btnChat_4)

        self.btnAccount_4 = QPushButton(self.horizontalLayoutWidget_5)
        self.btnAccount_4.setObjectName(u"btnAccount_4")
        self.btnAccount_4.setEnabled(True)
        icon14 = QIcon()
        icon14.addFile(u":/icons/icons/account-select.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btnAccount_4.setIcon(icon14)
        self.btnAccount_4.setIconSize(QSize(24, 24))

        self.horizontalLayout_7.addWidget(self.btnAccount_4)

        self.topbar_account = QWidget(self.page_2)
        self.topbar_account.setObjectName(u"topbar_account")
        self.topbar_account.setGeometry(QRect(0, 0, 400, 70))
        self.topbar_account.setStyleSheet(u"#topbar_account {\n"
"	border-bottom: 1px solid #d9d9d9;\n"
"}")
        self.text_profile = QLabel(self.topbar_account)
        self.text_profile.setObjectName(u"text_profile")
        self.text_profile.setGeometry(QRect(170, 30, 75, 22))
        self.text_profile.setFont(font5)
        self.text_profile.setStyleSheet(u"color: #2c2c2c")
        self.btnEdit = QPushButton(self.topbar_account)
        self.btnEdit.setObjectName(u"btnEdit")
        self.btnEdit.setGeometry(QRect(355, 35, 22, 18))
        self.btnEdit.setFont(font7)
        self.btnEdit.setStyleSheet(u"color: #EBCE38")
        self.scrollArea_4 = QScrollArea(self.page_2)
        self.scrollArea_4.setObjectName(u"scrollArea_4")
        self.scrollArea_4.setGeometry(QRect(0, 70, 400, 580))
        self.scrollArea_4.setStyleSheet(u"background-color: #ffffff")
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setObjectName(u"scrollAreaWidgetContents_4")
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 398, 578))
        self.label_mySchool = QLabel(self.scrollAreaWidgetContents_4)
        self.label_mySchool.setObjectName(u"label_mySchool")
        self.label_mySchool.setGeometry(QRect(20, 415, 41, 18))
        self.label_mySchool.setFont(font)
        self.label_mySchool.setStyleSheet(u"color: #454545")
        self.userImage = QLabel(self.scrollAreaWidgetContents_4)
        self.userImage.setObjectName(u"userImage")
        self.userImage.setGeometry(QRect(0, 0, 400, 400))
        self.userImage.setStyleSheet(u"background-color: #EBCE38")
        self.btnBkPhoto = QPushButton(self.scrollAreaWidgetContents_4)
        self.btnBkPhoto.setObjectName(u"btnBkPhoto")
        self.btnBkPhoto.setGeometry(QRect(145, 370, 50, 20))
        self.btnBkPhoto.setStyleSheet(u"background-color: rgba(255, 255, 255, 0.5);")
        self.label_myAge = QLabel(self.scrollAreaWidgetContents_4)
        self.label_myAge.setObjectName(u"label_myAge")
        self.label_myAge.setGeometry(QRect(42, 443, 13, 16))
        self.label_myAge.setStyleSheet(u"color: #707070")
        self.icon_myCake = QLabel(self.scrollAreaWidgetContents_4)
        self.icon_myCake.setObjectName(u"icon_myCake")
        self.icon_myCake.setGeometry(QRect(20, 440, 14, 17))
        self.icon_myCake.setPixmap(QPixmap(u":/icons/icons/cake.png"))
        self.hr1_3 = QFrame(self.scrollAreaWidgetContents_4)
        self.hr1_3.setObjectName(u"hr1_3")
        self.hr1_3.setGeometry(QRect(20, 460, 361, 20))
        self.hr1_3.setStyleSheet(u"color: #d9d9d9")
        self.hr1_3.setFrameShape(QFrame.HLine)
        self.hr1_3.setFrameShadow(QFrame.Raised)
        self.btnFwPhoto = QPushButton(self.scrollAreaWidgetContents_4)
        self.btnFwPhoto.setObjectName(u"btnFwPhoto")
        self.btnFwPhoto.setGeometry(QRect(205, 370, 50, 20))
        self.btnFwPhoto.setStyleSheet(u"background-color: rgba(255, 255, 255, 0.5);")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.textEditBio = QTextEdit(self.page_3)
        self.textEditBio.setObjectName(u"textEditBio")
        self.textEditBio.setGeometry(QRect(20, 450, 361, 71))
        self.textEditBio.setStyleSheet(u"")
        self.comboBoxMySchool = QComboBox(self.page_3)
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.addItem("")
        self.comboBoxMySchool.setObjectName(u"comboBoxMySchool")
        self.comboBoxMySchool.setGeometry(QRect(20, 590, 361, 31))
        self.comboBoxMySchool.setStyleSheet(u"color: #666666")
        self.topbar_edit = QWidget(self.page_3)
        self.topbar_edit.setObjectName(u"topbar_edit")
        self.topbar_edit.setGeometry(QRect(0, 0, 400, 70))
        self.topbar_edit.setStyleSheet(u"#topbar_edit {\n"
"	border-bottom: 1px solid #d9d9d9;\n"
"}")
        self.text_edit_profile = QLabel(self.topbar_edit)
        self.text_edit_profile.setObjectName(u"text_edit_profile")
        self.text_edit_profile.setGeometry(QRect(165, 30, 80, 22))
        self.text_edit_profile.setFont(font5)
        self.text_edit_profile.setStyleSheet(u"color: #2c2c2c")
        self.btnDone = QPushButton(self.topbar_edit)
        self.btnDone.setObjectName(u"btnDone")
        self.btnDone.setGeometry(QRect(350, 35, 31, 18))
        self.btnDone.setFont(font7)
        self.btnDone.setStyleSheet(u"color: #EBCE38")
        self.editPhoto5 = QLabel(self.page_3)
        self.editPhoto5.setObjectName(u"editPhoto5")
        self.editPhoto5.setGeometry(QRect(150, 330, 100, 100))
        self.editPhoto5.setCursor(QCursor(Qt.PointingHandCursor))
        self.editPhoto5.setStyleSheet(u"background-color: #d9d9d9")
        self.editPhoto5.setAlignment(Qt.AlignCenter)
        self.editPhoto4 = QLabel(self.page_3)
        self.editPhoto4.setObjectName(u"editPhoto4")
        self.editPhoto4.setGeometry(QRect(30, 330, 100, 100))
        self.editPhoto4.setCursor(QCursor(Qt.PointingHandCursor))
        self.editPhoto4.setStyleSheet(u"background-color: #d9d9d9")
        self.editPhoto4.setAlignment(Qt.AlignCenter)
        self.editPhoto6 = QLabel(self.page_3)
        self.editPhoto6.setObjectName(u"editPhoto6")
        self.editPhoto6.setGeometry(QRect(270, 330, 100, 100))
        self.editPhoto6.setCursor(QCursor(Qt.PointingHandCursor))
        self.editPhoto6.setStyleSheet(u"background-color: #d9d9d9")
        self.editPhoto6.setAlignment(Qt.AlignCenter)
        self.editPhoto1 = QLabel(self.page_3)
        self.editPhoto1.setObjectName(u"editPhoto1")
        self.editPhoto1.setGeometry(QRect(30, 90, 220, 220))
        self.editPhoto1.setFont(font1)
        self.editPhoto1.setCursor(QCursor(Qt.PointingHandCursor))
        self.editPhoto1.setStyleSheet(u"background-color: #d9d9d9")
        self.editPhoto1.setAlignment(Qt.AlignCenter)
        self.editPhoto3 = QLabel(self.page_3)
        self.editPhoto3.setObjectName(u"editPhoto3")
        self.editPhoto3.setGeometry(QRect(270, 210, 100, 100))
        self.editPhoto3.setCursor(QCursor(Qt.PointingHandCursor))
        self.editPhoto3.setStyleSheet(u"background-color: #d9d9d9")
        self.editPhoto3.setAlignment(Qt.AlignCenter)
        self.editPhoto2 = QLabel(self.page_3)
        self.editPhoto2.setObjectName(u"editPhoto2")
        self.editPhoto2.setGeometry(QRect(270, 90, 100, 100))
        self.editPhoto2.setFont(font4)
        self.editPhoto2.setCursor(QCursor(Qt.PointingHandCursor))
        self.editPhoto2.setStyleSheet(u"background-color: #d9d9d9")
        self.editPhoto2.setAlignment(Qt.AlignCenter)
        self.comboBoxMyRG = QComboBox(self.page_3)
        self.comboBoxMyRG.addItem("")
        self.comboBoxMyRG.addItem("")
        self.comboBoxMyRG.addItem("")
        self.comboBoxMyRG.addItem("")
        self.comboBoxMyRG.addItem("")
        self.comboBoxMyRG.setObjectName(u"comboBoxMyRG")
        self.comboBoxMyRG.setGeometry(QRect(20, 540, 361, 31))
        self.comboBoxMyRG.setStyleSheet(u"color: #666666")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)
        self.btnSignin.setDefault(False)
        self.btnSignup.setDefault(False)
        self.btnBackSignin.setDefault(False)
        self.btnBackSignup.setDefault(False)
        self.btnBackBD.setDefault(False)
        self.btnBackInfo.setDefault(False)
        self.comboBox_gender.setCurrentIndex(0)
        self.comboBox_showGender.setCurrentIndex(0)
        self.btnBackPhoto.setDefault(False)
        self.btnPreferences.setDefault(False)
        self.btnBackPref.setDefault(False)
        self.comboBoxRG.setCurrentIndex(0)
        self.btnBackChat.setDefault(False)
        self.comboBoxMySchool.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btnSignin.setText(QCoreApplication.translate("MainWindow", u"I've been here before", None))
        self.icon_daisy.setText("")
        self.text_description.setText(QCoreApplication.translate("MainWindow", u"Just buy them a daisy", None))
        self.btnSignup.setText(QCoreApplication.translate("MainWindow", u"I'm new here", None))
        self.text_daisydate.setText(QCoreApplication.translate("MainWindow", u"daisydate.", None))
        self.text_welcome.setText(QCoreApplication.translate("MainWindow", u"Welcome Back!", None))
        self.lineEdit_email.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter your email ", None))
        self.lineEdit_password.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter your password", None))
        self.btnBackSignin.setText("")
        self.btnSign_in.setText(QCoreApplication.translate("MainWindow", u"Let's find your daisy!", None))
        self.label_signin_error.setText(QCoreApplication.translate("MainWindow", u"Invalid email or password. Please try again.", None))
        self.btnBackSignup.setText("")
        self.text_welcome2.setText(QCoreApplication.translate("MainWindow", u"Welcome to daisydate!", None))
        self.btnGetStarted.setText(QCoreApplication.translate("MainWindow", u"Get Started", None))
        self.label_signup_error.setText(QCoreApplication.translate("MainWindow", u"Invalid email or password. Please try again.", None))
        self.lineEditPassword.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter your password", None))
        self.lineEditEmail.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter your email ", None))
        self.btnNext.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.label_bd.setText(QCoreApplication.translate("MainWindow", u"What's your birthday?", None))
        self.btnBackBD.setText("")
        self.label_age_error.setText(QCoreApplication.translate("MainWindow", u"Sorry, you must be at least 18 years old to use daisydate.", None))
        self.btnAlmostDone.setText(QCoreApplication.translate("MainWindow", u"Almost done!", None))
        self.text_info.setText(QCoreApplication.translate("MainWindow", u"Tell us about you!", None))
        self.btnBackInfo.setText("")
        self.lineEdit_name.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.comboBox_gender.setItemText(0, QCoreApplication.translate("MainWindow", u"Gender", None))
        self.comboBox_gender.setItemText(1, QCoreApplication.translate("MainWindow", u"Woman", None))
        self.comboBox_gender.setItemText(2, QCoreApplication.translate("MainWindow", u"Man", None))
        self.comboBox_gender.setItemText(3, QCoreApplication.translate("MainWindow", u"Other", None))

        self.comboBox_gender.setPlaceholderText("")
        self.comboBox_showGender.setItemText(0, QCoreApplication.translate("MainWindow", u"Show me", None))
        self.comboBox_showGender.setItemText(1, QCoreApplication.translate("MainWindow", u"Women", None))
        self.comboBox_showGender.setItemText(2, QCoreApplication.translate("MainWindow", u"Men", None))
        self.comboBox_showGender.setItemText(3, QCoreApplication.translate("MainWindow", u"Everyone", None))

        self.comboBox_showGender.setPlaceholderText("")
        self.btnWelcome.setText(QCoreApplication.translate("MainWindow", u"Welcome to daisydate!", None))
        self.text_add_photo.setText(QCoreApplication.translate("MainWindow", u"Add your photo!", None))
        self.btnBackPhoto.setText("")
        self.photo1.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.photo2.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.photo3.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.photo4.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.photo5.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.photo6.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.btnSuggested.setText("")
        self.btnDiscover.setText("")
        self.btnChat.setText("")
        self.btnAccount.setText("")
        self.text_suggested.setText(QCoreApplication.translate("MainWindow", u"Suggested", None))
        self.btnPreferences.setText("")
        self.user_image.setText("")
        self.label_age.setText(QCoreApplication.translate("MainWindow", u"20", None))
        self.label_school.setText(QCoreApplication.translate("MainWindow", u"School", None))
        self.icon_cake.setText("")
        self.btn_fw_photo.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.btn_bk_photo.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.btnDislike.setText("")
        self.btnFlower.setText("")
        self.btnLike.setText("")
        self.btnBackPref.setText("")
        self.text_type.setText(QCoreApplication.translate("MainWindow", u"What's your type?", None))
        self.text_preferences.setText(QCoreApplication.translate("MainWindow", u"Preferences help us personalize your daily bath in \n"
"Suggested. Changes apply on the next day.", None))
        self.comboBoxGender.setItemText(0, QCoreApplication.translate("MainWindow", u"Gender", None))
        self.comboBoxGender.setItemText(1, QCoreApplication.translate("MainWindow", u"Everyone", None))
        self.comboBoxGender.setItemText(2, QCoreApplication.translate("MainWindow", u"Women", None))
        self.comboBoxGender.setItemText(3, QCoreApplication.translate("MainWindow", u"Men", None))

        self.comboBoxGender.setPlaceholderText("")
        self.text_age.setText(QCoreApplication.translate("MainWindow", u"Age", None))
        self.text_to.setText(QCoreApplication.translate("MainWindow", u"to", None))
        self.comboBoxRG.setItemText(0, QCoreApplication.translate("MainWindow", u"Relationship Goals", None))
        self.comboBoxRG.setItemText(1, QCoreApplication.translate("MainWindow", u"Open to all", None))
        self.comboBoxRG.setItemText(2, QCoreApplication.translate("MainWindow", u"Marriage", None))
        self.comboBoxRG.setItemText(3, QCoreApplication.translate("MainWindow", u"A serious relationship", None))
        self.comboBoxRG.setItemText(4, QCoreApplication.translate("MainWindow", u"Something casual", None))

        self.comboBoxRG.setPlaceholderText("")
        self.text_discover.setText(QCoreApplication.translate("MainWindow", u"Discover", None))
        self.btnSearch.setText("")
        self.icon_flower.setText("")
        self.text_flower.setText(QCoreApplication.translate("MainWindow", u"500", None))
        self.btnSuggested_2.setText("")
        self.btnDiscover_2.setText("")
        self.btnChat_2.setText("")
        self.btnAccount_2.setText("")
        self.btnFlowerDiscover.setText("")
        self.label_photo.setText("")
        self.text_school.setText(QCoreApplication.translate("MainWindow", u"School", None))
        self.label_cake.setText("")
        self.label_age_discover.setText(QCoreApplication.translate("MainWindow", u"20", None))
        self.text_search.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.btnApply.setText(QCoreApplication.translate("MainWindow", u"Apply", None))
        self.btnCancel.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.label_age_search.setText(QCoreApplication.translate("MainWindow", u"Age", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"to", None))
        self.comboBox_school.setItemText(0, QCoreApplication.translate("MainWindow", u"School", None))
        self.comboBox_school.setItemText(1, QCoreApplication.translate("MainWindow", u"Open to all", None))
        self.comboBox_school.setItemText(2, QCoreApplication.translate("MainWindow", u"King Mongkut's Institute of Technology Ladkrabang", None))
        self.comboBox_school.setItemText(3, QCoreApplication.translate("MainWindow", u"Chulalongkorn University", None))
        self.comboBox_school.setItemText(4, QCoreApplication.translate("MainWindow", u"Thammasat University", None))
        self.comboBox_school.setItemText(5, QCoreApplication.translate("MainWindow", u"Kasetsart University", None))
        self.comboBox_school.setItemText(6, QCoreApplication.translate("MainWindow", u"Mahidol University", None))
        self.comboBox_school.setItemText(7, QCoreApplication.translate("MainWindow", u"Chiang Mai University", None))
        self.comboBox_school.setItemText(8, QCoreApplication.translate("MainWindow", u"Prince of Songkla University", None))
        self.comboBox_school.setItemText(9, QCoreApplication.translate("MainWindow", u"Khon Kaen University", None))
        self.comboBox_school.setItemText(10, QCoreApplication.translate("MainWindow", u"Asian Institute of Technology", None))
        self.comboBox_school.setItemText(11, QCoreApplication.translate("MainWindow", u"Suan Sunandha Rajabhat University", None))
        self.comboBox_school.setItemText(12, QCoreApplication.translate("MainWindow", u"King Mongkut's University of Technology Thonburi", None))
        self.comboBox_school.setItemText(13, QCoreApplication.translate("MainWindow", u"Ramkhamhaeng University", None))
        self.comboBox_school.setItemText(14, QCoreApplication.translate("MainWindow", u"Srinakharinwirot University", None))
        self.comboBox_school.setItemText(15, QCoreApplication.translate("MainWindow", u"Burapha University", None))
        self.comboBox_school.setItemText(16, QCoreApplication.translate("MainWindow", u"Naresuan University", None))
        self.comboBox_school.setItemText(17, QCoreApplication.translate("MainWindow", u"Silpakorn University", None))
        self.comboBox_school.setItemText(18, QCoreApplication.translate("MainWindow", u"Assumption University", None))
        self.comboBox_school.setItemText(19, QCoreApplication.translate("MainWindow", u"Suranaree University of Technology", None))
        self.comboBox_school.setItemText(20, QCoreApplication.translate("MainWindow", u"Sripatum University", None))
        self.comboBox_school.setItemText(21, QCoreApplication.translate("MainWindow", u"King Mongkut's University of Technology North Bangkok", None))
        self.comboBox_school.setItemText(22, QCoreApplication.translate("MainWindow", u"Rangsit University", None))
        self.comboBox_school.setItemText(23, QCoreApplication.translate("MainWindow", u"Bangkok University", None))

        self.comboBox_school.setPlaceholderText("")
        self.btnSuggested_3.setText("")
        self.btnDiscover_3.setText("")
        self.btnChat_3.setText("")
        self.btnAccount_3.setText("")
        self.text_chat.setText(QCoreApplication.translate("MainWindow", u"Chat", None))
        self.text_user_name.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.btnBackChat.setText("")
        self.lineEditChat.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Aa", None))
        self.btnSend.setText("")
        self.btnSuggested_4.setText("")
        self.btnDiscover_4.setText("")
        self.btnChat_4.setText("")
        self.btnAccount_4.setText("")
        self.text_profile.setText(QCoreApplication.translate("MainWindow", u"My Profile", None))
        self.btnEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.label_mySchool.setText(QCoreApplication.translate("MainWindow", u"School", None))
        self.userImage.setText("")
        self.btnBkPhoto.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.label_myAge.setText(QCoreApplication.translate("MainWindow", u"20", None))
        self.icon_myCake.setText("")
        self.btnFwPhoto.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.textEditBio.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Bio", None))
        self.comboBoxMySchool.setItemText(0, QCoreApplication.translate("MainWindow", u"School", None))
        self.comboBoxMySchool.setItemText(1, QCoreApplication.translate("MainWindow", u"King Mongkut's Institute of Technology Ladkrabang", None))
        self.comboBoxMySchool.setItemText(2, QCoreApplication.translate("MainWindow", u"Chulalongkorn University", None))
        self.comboBoxMySchool.setItemText(3, QCoreApplication.translate("MainWindow", u"Thammasat University", None))
        self.comboBoxMySchool.setItemText(4, QCoreApplication.translate("MainWindow", u"Kasetsart University", None))
        self.comboBoxMySchool.setItemText(5, QCoreApplication.translate("MainWindow", u"Mahidol University", None))
        self.comboBoxMySchool.setItemText(6, QCoreApplication.translate("MainWindow", u"Chiang Mai University", None))
        self.comboBoxMySchool.setItemText(7, QCoreApplication.translate("MainWindow", u"Prince of Songkla University", None))
        self.comboBoxMySchool.setItemText(8, QCoreApplication.translate("MainWindow", u"Khon Kaen University", None))
        self.comboBoxMySchool.setItemText(9, QCoreApplication.translate("MainWindow", u"Asian Institute of Technology", None))
        self.comboBoxMySchool.setItemText(10, QCoreApplication.translate("MainWindow", u"Suan Sunandha Rajabhat University", None))
        self.comboBoxMySchool.setItemText(11, QCoreApplication.translate("MainWindow", u"King Mongkut's University of Technology Thonburi", None))
        self.comboBoxMySchool.setItemText(12, QCoreApplication.translate("MainWindow", u"Ramkhamhaeng University", None))
        self.comboBoxMySchool.setItemText(13, QCoreApplication.translate("MainWindow", u"Srinakharinwirot University", None))
        self.comboBoxMySchool.setItemText(14, QCoreApplication.translate("MainWindow", u"Burapha University", None))
        self.comboBoxMySchool.setItemText(15, QCoreApplication.translate("MainWindow", u"Naresuan University", None))
        self.comboBoxMySchool.setItemText(16, QCoreApplication.translate("MainWindow", u"Silpakorn University", None))
        self.comboBoxMySchool.setItemText(17, QCoreApplication.translate("MainWindow", u"Assumption University", None))
        self.comboBoxMySchool.setItemText(18, QCoreApplication.translate("MainWindow", u"Suranaree University of Technology", None))
        self.comboBoxMySchool.setItemText(19, QCoreApplication.translate("MainWindow", u"Sripatum University", None))
        self.comboBoxMySchool.setItemText(20, QCoreApplication.translate("MainWindow", u"King Mongkut's University of Technology North Bangkok", None))
        self.comboBoxMySchool.setItemText(21, QCoreApplication.translate("MainWindow", u"Rangsit University", None))
        self.comboBoxMySchool.setItemText(22, QCoreApplication.translate("MainWindow", u"Bangkok University", None))

        self.comboBoxMySchool.setPlaceholderText(QCoreApplication.translate("MainWindow", u"School", None))
        self.text_edit_profile.setText(QCoreApplication.translate("MainWindow", u"Edit Profile", None))
        self.btnDone.setText(QCoreApplication.translate("MainWindow", u"Done", None))
        self.editPhoto5.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.editPhoto4.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.editPhoto6.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.editPhoto1.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.editPhoto3.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.editPhoto2.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.comboBoxMyRG.setItemText(0, QCoreApplication.translate("MainWindow", u"Relationship Goals", None))
        self.comboBoxMyRG.setItemText(1, QCoreApplication.translate("MainWindow", u"Marriage", None))
        self.comboBoxMyRG.setItemText(2, QCoreApplication.translate("MainWindow", u"A serious relationship", None))
        self.comboBoxMyRG.setItemText(3, QCoreApplication.translate("MainWindow", u"Something casual", None))
        self.comboBoxMyRG.setItemText(4, QCoreApplication.translate("MainWindow", u"Not sure yet", None))

        self.comboBoxMyRG.setPlaceholderText("")
    # retranslateUi

